 version: 2

 build:
   os: "ubuntu-24.04"
   tools:
     python: "3.11"
   jobs:
     pre_install:
       - python -m pip install --upgrade pip
       - python -m pip install '.[docs]'

 mkdocs:
   configuration: mkdocs.yml