[project]
name = "bbob-jax"
version = "0.1.0"
description = "BBOB Benchmark function implemented in JAX"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jax",
    "jaxtyping>=0.3.3",
]

[dependency-groups]
dev = [
    "matplotlib>=3.10.7",
]
